component_depth: 1
languages:
- java
exclude:
- ./bin/.*
- ./bin/async/.*
- ./bin/cal/.*
- ./bin/chat/.*
- ./bin/checkbox/.*
- ./bin/colors/.*
- ./bin/compressionFilters/.*
- ./bin/dates/.*
- ./bin/error/.*
- ./bin/examples/.*
- ./bin/filters/.*
- ./bin/javax/.*
- ./bin/javax/annotation/.*
- ./bin/javax/annotation/security/.*
- ./bin/javax/ejb/.*
- ./bin/javax/el/.*
- ./bin/javax/mail/.*
- ./bin/javax/mail/internet/.*
- ./bin/javax/persistence/.*
- ./bin/javax/servlet/.*
- ./bin/javax/servlet/annotation/.*
- ./bin/javax/servlet/descriptor/.*
- ./bin/javax/servlet/http/.*
- ./bin/javax/servlet/jsp/.*
- ./bin/javax/servlet/jsp/el/.*
- ./bin/javax/servlet/jsp/tagext/.*
- ./bin/javax/servlet/jsp/tagext/doc-files/.*
- ./bin/javax/xml/.*
- ./bin/javax/xml/ws/.*
- ./bin/jsp2/.*
- ./bin/jsp2/examples/.*
- ./bin/jsp2/examples/el/.*
- ./bin/jsp2/examples/simpletag/.*
- ./bin/listeners/.*
- ./bin/mypackage/.*
- ./bin/num/.*
- ./bin/org/.*
- ./bin/org/apache/.*
- ./bin/org/apache/catalina/.*
- ./bin/org/apache/catalina/ant/.*
- ./bin/org/apache/catalina/ant/jmx/.*
- ./bin/org/apache/catalina/authenticator/.*
- ./bin/org/apache/catalina/comet/.*
- ./bin/org/apache/catalina/connector/.*
- ./bin/org/apache/catalina/core/.*
- ./bin/org/apache/catalina/deploy/.*
- ./bin/org/apache/catalina/filters/.*
- ./bin/org/apache/catalina/ha/.*
- ./bin/org/apache/catalina/ha/authenticator/.*
- ./bin/org/apache/catalina/ha/backend/.*
- ./bin/org/apache/catalina/ha/context/.*
- ./bin/org/apache/catalina/ha/deploy/.*
- ./bin/org/apache/catalina/ha/jmx/.*
- ./bin/org/apache/catalina/ha/session/.*
- ./bin/org/apache/catalina/ha/tcp/.*
- ./bin/org/apache/catalina/ha/util/.*
- ./bin/org/apache/catalina/loader/.*
- ./bin/org/apache/catalina/manager/.*
- ./bin/org/apache/catalina/manager/host/.*
- ./bin/org/apache/catalina/manager/util/.*
- ./bin/org/apache/catalina/mbeans/.*
- ./bin/org/apache/catalina/realm/.*
- ./bin/org/apache/catalina/security/.*
- ./bin/org/apache/catalina/servlets/.*
- ./bin/org/apache/catalina/session/.*
- ./bin/org/apache/catalina/ssi/.*
- ./bin/org/apache/catalina/startup/.*
- ./bin/org/apache/catalina/tribes/.*
- ./bin/org/apache/catalina/tribes/demos/.*
- ./bin/org/apache/catalina/tribes/group/.*
- ./bin/org/apache/catalina/tribes/group/interceptors/.*
- ./bin/org/apache/catalina/tribes/io/.*
- ./bin/org/apache/catalina/tribes/membership/.*
- ./bin/org/apache/catalina/tribes/test/.*
- ./bin/org/apache/catalina/tribes/test/channel/.*
- ./bin/org/apache/catalina/tribes/test/interceptors/.*
- ./bin/org/apache/catalina/tribes/test/io/.*
- ./bin/org/apache/catalina/tribes/test/membership/.*
- ./bin/org/apache/catalina/tribes/test/transport/.*
- ./bin/org/apache/catalina/tribes/tipis/.*
- ./bin/org/apache/catalina/tribes/transport/.*
- ./bin/org/apache/catalina/tribes/transport/bio/.*
- ./bin/org/apache/catalina/tribes/transport/bio/util/.*
- ./bin/org/apache/catalina/tribes/transport/nio/.*
- ./bin/org/apache/catalina/tribes/util/.*
- ./bin/org/apache/catalina/users/.*
- ./bin/org/apache/catalina/util/.*
- ./bin/org/apache/catalina/valves/.*
- ./bin/org/apache/coyote/.*
- ./bin/org/apache/coyote/ajp/.*
- ./bin/org/apache/coyote/http11/.*
- ./bin/org/apache/coyote/http11/filters/.*
- ./bin/org/apache/el/.*
- ./bin/org/apache/el/lang/.*
- ./bin/org/apache/el/parser/.*
- ./bin/org/apache/el/util/.*
- ./bin/org/apache/jasper/.*
- ./bin/org/apache/jasper/compiler/.*
- ./bin/org/apache/jasper/compiler/tagplugin/.*
- ./bin/org/apache/jasper/el/.*
- ./bin/org/apache/jasper/runtime/.*
- ./bin/org/apache/jasper/security/.*
- ./bin/org/apache/jasper/servlet/.*
- ./bin/org/apache/jasper/tagplugins/.*
- ./bin/org/apache/jasper/tagplugins/jstl/.*
- ./bin/org/apache/jasper/tagplugins/jstl/core/.*
- ./bin/org/apache/jasper/util/.*
- ./bin/org/apache/jasper/xmlparser/.*
- ./bin/org/apache/juli/.*
- ./bin/org/apache/juli/logging/.*
- ./bin/org/apache/naming/.*
- ./bin/org/apache/naming/factory/.*
- ./bin/org/apache/naming/factory/webservices/.*
- ./bin/org/apache/naming/java/.*
- ./bin/org/apache/tomcat/.*
- ./bin/org/apache/tomcat/buildutil/.*
- ./bin/org/apache/tomcat/jni/.*
- ./bin/org/apache/tomcat/util/.*
- ./bin/org/apache/tomcat/util/bcel/.*
- ./bin/org/apache/tomcat/util/bcel/classfile/.*
- ./bin/org/apache/tomcat/util/bcel/util/.*
- ./bin/org/apache/tomcat/util/buf/.*
- ./bin/org/apache/tomcat/util/buf/res/.*
- ./bin/org/apache/tomcat/util/collections/.*
- ./bin/org/apache/tomcat/util/digester/.*
- ./bin/org/apache/tomcat/util/http/.*
- ./bin/org/apache/tomcat/util/http/fileupload/.*
- ./bin/org/apache/tomcat/util/http/fileupload/disk/.*
- ./bin/org/apache/tomcat/util/http/fileupload/servlet/.*
- ./bin/org/apache/tomcat/util/http/fileupload/util/.*
- ./bin/org/apache/tomcat/util/http/mapper/.*
- ./bin/org/apache/tomcat/util/http/res/.*
- ./bin/org/apache/tomcat/util/log/.*
- ./bin/org/apache/tomcat/util/modeler/.*
- ./bin/org/apache/tomcat/util/modeler/modules/.*
- ./bin/org/apache/tomcat/util/net/.*
- ./bin/org/apache/tomcat/util/net/jsse/.*
- ./bin/org/apache/tomcat/util/net/jsse/res/.*
- ./bin/org/apache/tomcat/util/net/res/.*
- ./bin/org/apache/tomcat/util/res/.*
- ./bin/org/apache/tomcat/util/scan/.*
- ./bin/org/apache/tomcat/util/threads/.*
- ./bin/org/apache/tomcat/util/threads/res/.*
- ./bin/sessions/.*
- ./bin/util/.*
- ./bin/validators/.*
- ./bin/webapp-2.3/.*
- ./bin/webapp-2.3/WEB-INF/.*
- ./bin/webapp-2.4/.*
- ./bin/webapp-2.4/WEB-INF/.*
- ./bin/webapp-2.5/.*
- ./bin/webapp-2.5/WEB-INF/.*
- ./bin/webapp-3.0/.*
- ./bin/webapp-3.0/WEB-INF/.*
- ./bin/webapp-3.0/WEB-INF/tags/.*
- ./bin/webapp-3.0/bug45nnn/.*
- ./bin/webapp-3.0/bug48nnn/.*
- ./bin/webapp-3.0-fragments/.*
- ./bin/webapp-3.0-fragments/WEB-INF/.*
- ./bin/webapp-3.0-fragments/WEB-INF/lib/.*
- ./bin/webapp-3.0-fragments/folder/.*
- ./conf/.*
- ./java/.*
- ./java/javax/.*
- ./java/javax/annotation/.*
- ./java/javax/annotation/security/.*
- ./java/javax/ejb/.*
- ./java/javax/el/.*
- ./java/javax/mail/.*
- ./java/javax/mail/internet/.*
- ./java/javax/persistence/.*
- ./java/javax/servlet/.*
- ./java/javax/servlet/annotation/.*
- ./java/javax/servlet/descriptor/.*
- ./java/javax/servlet/http/.*
- ./java/javax/servlet/jsp/.*
- ./java/javax/servlet/jsp/el/.*
- ./java/javax/servlet/jsp/tagext/.*
- ./java/javax/servlet/jsp/tagext/doc-files/.*
- ./java/javax/xml/.*
- ./java/javax/xml/ws/.*
- ./java/org/.*
- ./java/org/apache/.*
- ./java/org/apache/catalina/.*
- ./java/org/apache/catalina/ant/.*
- ./java/org/apache/catalina/ant/jmx/.*
- ./java/org/apache/catalina/authenticator/.*
- ./java/org/apache/catalina/comet/.*
- ./java/org/apache/catalina/connector/.*
- ./java/org/apache/catalina/core/.*
- ./java/org/apache/catalina/deploy/.*
- ./java/org/apache/catalina/filters/.*
- ./java/org/apache/catalina/ha/.*
- ./java/org/apache/catalina/ha/authenticator/.*
- ./java/org/apache/catalina/ha/backend/.*
- ./java/org/apache/catalina/ha/context/.*
- ./java/org/apache/catalina/ha/deploy/.*
- ./java/org/apache/catalina/ha/jmx/.*
- ./java/org/apache/catalina/ha/session/.*
- ./java/org/apache/catalina/ha/tcp/.*
- ./java/org/apache/catalina/ha/util/.*
- ./java/org/apache/catalina/loader/.*
- ./java/org/apache/catalina/manager/.*
- ./java/org/apache/catalina/manager/host/.*
- ./java/org/apache/catalina/manager/util/.*
- ./java/org/apache/catalina/mbeans/.*
- ./java/org/apache/catalina/realm/.*
- ./java/org/apache/catalina/security/.*
- ./java/org/apache/catalina/servlets/.*
- ./java/org/apache/catalina/session/.*
- ./java/org/apache/catalina/ssi/.*
- ./java/org/apache/catalina/startup/.*
- ./java/org/apache/catalina/tribes/.*
- ./java/org/apache/catalina/tribes/group/.*
- ./java/org/apache/catalina/tribes/group/interceptors/.*
- ./java/org/apache/catalina/tribes/io/.*
- ./java/org/apache/catalina/tribes/membership/.*
- ./java/org/apache/catalina/tribes/tipis/.*
- ./java/org/apache/catalina/tribes/transport/.*
- ./java/org/apache/catalina/tribes/transport/bio/.*
- ./java/org/apache/catalina/tribes/transport/bio/util/.*
- ./java/org/apache/catalina/tribes/transport/nio/.*
- ./java/org/apache/catalina/tribes/util/.*
- ./java/org/apache/catalina/users/.*
- ./java/org/apache/catalina/util/.*
- ./java/org/apache/catalina/valves/.*
- ./java/org/apache/coyote/.*
- ./java/org/apache/coyote/ajp/.*
- ./java/org/apache/coyote/http11/.*
- ./java/org/apache/coyote/http11/filters/.*
- ./java/org/apache/el/.*
- ./java/org/apache/el/lang/.*
- ./java/org/apache/el/parser/.*
- ./java/org/apache/el/util/.*
- ./java/org/apache/jasper/.*
- ./java/org/apache/jasper/compiler/.*
- ./java/org/apache/jasper/compiler/tagplugin/.*
- ./java/org/apache/jasper/el/.*
- ./java/org/apache/jasper/runtime/.*
- ./java/org/apache/jasper/security/.*
- ./java/org/apache/jasper/servlet/.*
- ./java/org/apache/jasper/tagplugins/.*
- ./java/org/apache/jasper/tagplugins/jstl/.*
- ./java/org/apache/jasper/tagplugins/jstl/core/.*
- ./java/org/apache/jasper/util/.*
- ./java/org/apache/jasper/xmlparser/.*
- ./java/org/apache/juli/.*
- ./java/org/apache/juli/logging/.*
- ./java/org/apache/naming/.*
- ./java/org/apache/naming/factory/.*
- ./java/org/apache/naming/factory/webservices/.*
- ./java/org/apache/naming/java/.*
- ./java/org/apache/tomcat/.*
- ./java/org/apache/tomcat/buildutil/.*
- ./java/org/apache/tomcat/jni/.*
- ./java/org/apache/tomcat/util/.*
- ./java/org/apache/tomcat/util/bcel/.*
- ./java/org/apache/tomcat/util/bcel/classfile/.*
- ./java/org/apache/tomcat/util/bcel/util/.*
- ./java/org/apache/tomcat/util/buf/.*
- ./java/org/apache/tomcat/util/buf/res/.*
- ./java/org/apache/tomcat/util/collections/.*
- ./java/org/apache/tomcat/util/digester/.*
- ./java/org/apache/tomcat/util/http/.*
- ./java/org/apache/tomcat/util/http/fileupload/.*
- ./java/org/apache/tomcat/util/http/fileupload/disk/.*
- ./java/org/apache/tomcat/util/http/fileupload/servlet/.*
- ./java/org/apache/tomcat/util/http/fileupload/util/.*
- ./java/org/apache/tomcat/util/http/mapper/.*
- ./java/org/apache/tomcat/util/http/res/.*
- ./java/org/apache/tomcat/util/log/.*
- ./java/org/apache/tomcat/util/modeler/.*
- ./java/org/apache/tomcat/util/modeler/modules/.*
- ./java/org/apache/tomcat/util/net/.*
- ./java/org/apache/tomcat/util/net/jsse/.*
- ./java/org/apache/tomcat/util/net/jsse/res/.*
- ./java/org/apache/tomcat/util/net/res/.*
- ./java/org/apache/tomcat/util/res/.*
- ./java/org/apache/tomcat/util/scan/.*
- ./java/org/apache/tomcat/util/threads/.*
- ./java/org/apache/tomcat/util/threads/res/.*
- ./lib/.*
- ./res/.*
- ./res/META-INF/.*
- ./res/confinstall/.*
- ./res/deployer/.*
- ./res/maven/.*
- ./test/.*
- ./test/javax/.*
- ./test/javax/servlet/.*
- ./test/javax/servlet/jsp/.*
- ./test/org/.*
- ./test/org/apache/.*
- ./test/org/apache/catalina/.*
- ./test/org/apache/catalina/connector/.*
- ./test/org/apache/catalina/core/.*
- ./test/org/apache/catalina/deploy/.*
- ./test/org/apache/catalina/filters/.*
- ./test/org/apache/catalina/ha/.*
- ./test/org/apache/catalina/ha/session/.*
- ./test/org/apache/catalina/loader/.*
- ./test/org/apache/catalina/mbeans/.*
- ./test/org/apache/catalina/startup/.*
- ./test/org/apache/catalina/tribes/.*
- ./test/org/apache/catalina/tribes/demos/.*
- ./test/org/apache/catalina/tribes/test/.*
- ./test/org/apache/catalina/tribes/test/channel/.*
- ./test/org/apache/catalina/tribes/test/interceptors/.*
- ./test/org/apache/catalina/tribes/test/io/.*
- ./test/org/apache/catalina/tribes/test/membership/.*
- ./test/org/apache/catalina/tribes/test/transport/.*
- ./test/org/apache/catalina/util/.*
- ./test/org/apache/catalina/valves/.*
- ./test/org/apache/coyote/.*
- ./test/org/apache/coyote/http11/.*
- ./test/org/apache/el/.*
- ./test/org/apache/el/lang/.*
- ./test/org/apache/el/parser/.*
- ./test/org/apache/jasper/.*
- ./test/org/apache/jasper/compiler/.*
- ./test/org/apache/naming/.*
- ./test/org/apache/tomcat/.*
- ./test/org/apache/tomcat/util/.*
- ./test/org/apache/tomcat/util/buf/.*
- ./test/org/apache/tomcat/util/http/.*
- ./test/org/apache/tomcat/util/res/.*
- ./test/webapp-2.3/.*
- ./test/webapp-2.3/WEB-INF/.*
- ./test/webapp-2.4/.*
- ./test/webapp-2.4/WEB-INF/.*
- ./test/webapp-2.5/.*
- ./test/webapp-2.5/WEB-INF/.*
- ./test/webapp-3.0/.*
- ./test/webapp-3.0/WEB-INF/.*
- ./test/webapp-3.0/WEB-INF/tags/.*
- ./test/webapp-3.0/bug45nnn/.*
- ./test/webapp-3.0/bug48nnn/.*
- ./test/webapp-3.0-fragments/.*
- ./test/webapp-3.0-fragments/WEB-INF/.*
- ./test/webapp-3.0-fragments/WEB-INF/lib/.*
- ./test/webapp-3.0-fragments/folder/.*
- ./webapps/.*
- ./webapps/ROOT/.*
- ./webapps/ROOT/WEB-INF/.*
- ./webapps/docs/.*
- ./webapps/docs/META-INF/.*
- ./webapps/docs/WEB-INF/.*
- ./webapps/docs/api/.*
- ./webapps/docs/appdev/.*
- ./webapps/docs/appdev/sample/.*
- ./webapps/docs/appdev/sample/docs/.*
- ./webapps/docs/appdev/sample/web/.*
- ./webapps/docs/appdev/sample/web/WEB-INF/.*
- ./webapps/docs/appdev/sample/web/images/.*
- ./webapps/docs/architecture/.*
- ./webapps/docs/architecture/requestProcess/.*
- ./webapps/docs/architecture/startup/.*
- ./webapps/docs/config/.*
- ./webapps/docs/elapi/.*
- ./webapps/docs/funcspecs/.*
- ./webapps/docs/images/.*
- ./webapps/docs/jspapi/.*
- ./webapps/docs/servletapi/.*
- ./webapps/docs/tribes/.*
- ./webapps/examples/.*
- ./webapps/examples/WEB-INF/.*
- ./webapps/examples/WEB-INF/classes/.*
- ./webapps/examples/WEB-INF/classes/async/.*
- ./webapps/examples/WEB-INF/classes/cal/.*
- ./webapps/examples/WEB-INF/classes/chat/.*
- ./webapps/examples/WEB-INF/classes/checkbox/.*
- ./webapps/examples/WEB-INF/classes/colors/.*
- ./webapps/examples/WEB-INF/classes/compressionFilters/.*
- ./webapps/examples/WEB-INF/classes/dates/.*
- ./webapps/examples/WEB-INF/classes/error/.*
- ./webapps/examples/WEB-INF/classes/examples/.*
- ./webapps/examples/WEB-INF/classes/filters/.*
- ./webapps/examples/WEB-INF/classes/jsp2/.*
- ./webapps/examples/WEB-INF/classes/jsp2/examples/.*
- ./webapps/examples/WEB-INF/classes/jsp2/examples/el/.*
- ./webapps/examples/WEB-INF/classes/jsp2/examples/simpletag/.*
- ./webapps/examples/WEB-INF/classes/listeners/.*
- ./webapps/examples/WEB-INF/classes/num/.*
- ./webapps/examples/WEB-INF/classes/sessions/.*
- ./webapps/examples/WEB-INF/classes/util/.*
- ./webapps/examples/WEB-INF/classes/validators/.*
- ./webapps/examples/WEB-INF/jsp/.*
- ./webapps/examples/WEB-INF/jsp/applet/.*
- ./webapps/examples/WEB-INF/jsp2/.*
- ./webapps/examples/WEB-INF/lib/.*
- ./webapps/examples/WEB-INF/tags/.*
- ./webapps/examples/jsp/.*
- ./webapps/examples/jsp/async/.*
- ./webapps/examples/jsp/cal/.*
- ./webapps/examples/jsp/chat/.*
- ./webapps/examples/jsp/checkbox/.*
- ./webapps/examples/jsp/colors/.*
- ./webapps/examples/jsp/dates/.*
- ./webapps/examples/jsp/error/.*
- ./webapps/examples/jsp/forward/.*
- ./webapps/examples/jsp/images/.*
- ./webapps/examples/jsp/include/.*
- ./webapps/examples/jsp/jsp2/.*
- ./webapps/examples/jsp/jsp2/el/.*
- ./webapps/examples/jsp/jsp2/jspattribute/.*
- ./webapps/examples/jsp/jsp2/jspx/.*
- ./webapps/examples/jsp/jsp2/misc/.*
- ./webapps/examples/jsp/jsp2/simpletag/.*
- ./webapps/examples/jsp/jsp2/tagfiles/.*
- ./webapps/examples/jsp/jsptoserv/.*
- ./webapps/examples/jsp/num/.*
- ./webapps/examples/jsp/plugin/.*
- ./webapps/examples/jsp/plugin/applet/.*
- ./webapps/examples/jsp/security/.*
- ./webapps/examples/jsp/security/protected/.*
- ./webapps/examples/jsp/sessions/.*
- ./webapps/examples/jsp/simpletag/.*
- ./webapps/examples/jsp/snp/.*
- ./webapps/examples/jsp/tagplugin/.*
- ./webapps/examples/jsp/xml/.*
- ./webapps/examples/servlets/.*
- ./webapps/examples/servlets/images/.*
- ./webapps/host-manager/.*
- ./webapps/host-manager/META-INF/.*
- ./webapps/host-manager/WEB-INF/.*
- ./webapps/host-manager/images/.*
- ./webapps/manager/.*
- ./webapps/manager/META-INF/.*
- ./webapps/manager/WEB-INF/.*
- ./webapps/manager/WEB-INF/jsp/.*
- ./webapps/manager/images/.*
